# -*- coding: utf-8 -*-
"""hasankısmı.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3y3EzcqH9P4vgc4NqeTcvNW_uPHqlKl
"""

# Kaggle kütüphanesini yükle/güncelle
!pip install -q kaggle

# Bilgisayarına inen kaggle.json dosyasını seçip yüklemeni sağlar
from google.colab import files
files.upload()

# Kaggle klasörünü oluştur ve API anahtarını kopyala
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Veri setini indir (zip dosyası olarak iner)
!kaggle competitions download -c home-credit-default-risk

# Sadece ihtiyacın olan dosyaları zipten çıkar
# Not: Yarışmada 'application.csv' yerine 'application_train.csv' ve 'application_test.csv' bulunur.
!unzip home-credit-default-risk.zip application_train.csv application_test.csv bureau.csv bureau_balance.csv

# İstersen yer kaplamaması için zip dosyasını silebilirsin
!rm home-credit-default-risk.zip

import pandas as pd
import numpy as np

bureau = pd.read_csv('bureau.csv')
bureau_balance = pd.read_csv('bureau_balance.csv')

print("Bureau tablosu boyutu:", bureau.shape)
print("Bureau Balance tablosu boyutu:", bureau_balance.shape)

# Veriye hızlıca göz atalım
display(bureau_balance.head(3))

"""burdan sonra yeni denemeye başlıyoruz."""

bureau.shape

bb = pd.read_csv('bureau_balance.csv')

print("Orijinal bureau_balance boyutu:", bb.shape)

# 2. STATUS sütunundaki harfleri ve rakamları matematiksel işleme uygun hale getirelim.
# 'C' (Closed/Kapalı) ve 'X' (Bilinmiyor) durumlarını risksiz kabul edip 0 yapıyoruz.
# '0' zaten gecikme yok demek, o da 0.
# '1, 2, 3, 4, 5' ise gecikme aylarını temsil ediyor, onları direkt sayıya çeviriyoruz.
status_mapping = {'C': 0, 'X': 0, '0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5}

# Mapping işlemini uygulayıp yeni bir sayısal sütun yaratıyoruz
bb['STATUS_SCORE'] = bb['STATUS'].map(status_mapping)

# 3. Her bir Kredi ID'sine (SK_ID_BUREAU) göre gruplayıp sadece en kritik 3 özeti çıkarıyoruz:
bb_clean = bb.groupby('SK_ID_BUREAU').agg(
    BB_MONTH_COUNT=('MONTHS_BALANCE', 'count'),       # 1. Kredi toplam kaç ay sürmüş/kayıtlı?
    BB_MAX_OVERDUE_LEVEL=('STATUS_SCORE', 'max'),     # 2. Bu kredi tarihinde en fazla kaçıncı seviye gecikmeye düşmüş?
    BB_TOTAL_OVERDUE_SCORE=('STATUS_SCORE', 'sum')    # 3. Toplam gecikme skoru (Gecikmede geçen ayların toplam ağırlığı)
).reset_index()

print("\nTertemiz bureau_balance özet tablosu hazır! Yeni boyut:", bb_clean.shape)
display(bb_clean.head(20))

# Taha yasin deneme
bureau.info()

(bureau.isnull().sum() / len(bureau)) * 100

bureau.drop(["AMT_ANNUITY","AMT_CREDIT_MAX_OVERDUE"],axis=1,inplace=True)

(bureau.isnull().sum() / len(bureau)) * 100

bb_clean.isna().sum()

# 2. SADECE Para Birimi (CREDIT_CURRENCY) sütununu siliyoruz
bureau_clean = bureau.drop(columns=['CREDIT_CURRENCY'])

# 3. Sütun isimlerini Türkçe anlamlarıyla güncelliyoruz
yeni_isimler = {
    'SK_ID_CURR': 'SK_ID_CURR (Ana Müşteri ID)',
    'SK_ID_BUREAU': 'SK_ID_BUREAU (Kredi ID)',
    'CREDIT_ACTIVE': 'CREDIT_ACTIVE (Kredi Durumu)',
    'DAYS_CREDIT': 'DAYS_CREDIT (Kredinin Çekildiği Gün)',
    'CREDIT_DAY_OVERDUE': 'CREDIT_DAY_OVERDUE (Gecikme Günü)',
    'DAYS_CREDIT_ENDDATE': 'DAYS_CREDIT_ENDDATE (Planlanan Bitiş Günü)',
    'DAYS_ENDDATE_FACT': 'DAYS_ENDDATE_FACT (Fiili Kapanış Günü)',
    'CNT_CREDIT_PROLONG': 'CNT_CREDIT_PROLONG (Vade Uzatma Sayısı)',
    'AMT_CREDIT_SUM': 'AMT_CREDIT_SUM (Toplam Kredi Limiti)',
    'AMT_CREDIT_SUM_DEBT': 'AMT_CREDIT_SUM_DEBT (Güncel Kalan Borç)',
    'AMT_CREDIT_SUM_LIMIT': 'AMT_CREDIT_SUM_LIMIT (Kredi Kartı Limiti)',
    'AMT_CREDIT_SUM_OVERDUE': 'AMT_CREDIT_SUM_OVERDUE (Gecikmiş Tutar)',
    'CREDIT_TYPE': 'CREDIT_TYPE (Kredi Türü)',
    'DAYS_CREDIT_UPDATE': 'DAYS_CREDIT_UPDATE (Son Güncelleme Günü)'
}

bureau_clean.rename(columns=yeni_isimler, inplace=True)

# 4. MODEL EĞİTİMİNE HAZIRLIK: Metinleri sayıya çevirme (One-Hot Encoding)
# Makinenin okuyabilmesi için metin içeren 'Kredi Türü' ve 'Kredi Durumu' sütunlarını dönüştürüyoruz
bureau_model_ready = pd.get_dummies(bureau_clean, columns=['CREDIT_TYPE (Kredi Türü)', 'CREDIT_ACTIVE (Kredi Durumu)'])

print("İşlem tamam! Sadece para birimi silindi, sütunlar isimlendirildi ve model için sayısallaştırıldı.\n")
display(bureau_model_ready.head())

bureau_clean.drop("CREDIT_DAY_OVERDUE (Gecikme Günü)",axis=1,inplace=True)

bureau_clean.drop("AMT_CREDIT_SUM_LIMIT (Kredi Kartı Limiti)",axis=1,inplace=True)

bureau_merged = pd.merge(
    bureau_model_ready,
    bb_clean,
    how='left',
    left_on='SK_ID_BUREAU (Kredi ID)', # Bureau tablosunda adını böyle değiştirmiştik
    right_on='SK_ID_BUREAU'            # Balance tablosundaki orijinal adı
)
bureau_merged.drop(columns=['SK_ID_BUREAU'], inplace=True)

bureau_merged.head(10)

bureau_merged.info()

# Eksik verilerin yüzdelik oranını hesaplayıp, virgülden sonra 2 basamak olacak şekilde yuvarlıyoruz
eksik_oranlari = (bureau_merged.isna().mean() * 100).round(2)

print("Sütunlardaki Boş (NaN) Veri Oranları (%):\n")
print(eksik_oranlari.sort_values(ascending=False)) # En çok boşluk olanı en üste koyar

"""burdan sonrasında yeni yapılan değişiklikler bulunuyor traine ekleme yapılabilmesi için"""

# Sütun adını arkadaşının tablosuyla kolay eşleşmesi için orijinal haline (SK_ID_CURR) getirelim
bureau_merged.rename(columns={'SK_ID_CURR (Ana Müşteri ID)': 'SK_ID_CURR'}, inplace=True)

# Her bir müşteri için geçmiş kredi verilerini özetliyoruz
# (Burada mantığına göre ortalama 'mean', toplam 'sum' veya maksimum 'max' alabilirsin)
bureau_agg = bureau_merged.groupby('SK_ID_CURR').agg({
    'DAYS_CREDIT (Kredinin Çekildiği Gün)': 'mean',
    'AMT_CREDIT_SUM (Toplam Kredi Limiti)': 'sum',
    'AMT_CREDIT_SUM_DEBT (Güncel Kalan Borç)': 'sum',
    'AMT_CREDIT_SUM_OVERDUE (Gecikmiş Tutar)': 'sum',
    'CNT_CREDIT_PROLONG (Vade Uzatma Sayısı)': 'sum',
    'BB_MONTH_COUNT': 'mean',
    'BB_MAX_OVERDUE_LEVEL': 'max',
    'BB_TOTAL_OVERDUE_SCORE': 'sum',
    # One-hot encode ettiğin sütunların toplamını alarak "bu kişide bu kredi türünden kaç tane var" bilgisini elde ediyoruz
    'CREDIT_TYPE (Kredi Türü)_Consumer credit': 'sum',
    'CREDIT_TYPE (Kredi Türü)_Credit card': 'sum',
    'CREDIT_ACTIVE (Kredi Durumu)_Active': 'sum',
    'CREDIT_ACTIVE (Kredi Durumu)_Closed': 'sum'
}).reset_index()

# Sütun isimlerine "BUREAU_" ön eki ekleyelim ki arkadaşının ana tablosundaki verilerle isimleri çakışmasın
bureau_agg.columns = ['BUREAU_' + col if col != 'SK_ID_CURR' else col for col in bureau_agg.columns]

pd.set_option('display.max_columns', None)

bureau_merged.head()

bureau_merged.shape

# 1. Her bir değişken için hangi istatistiği alacağımızı belirliyoruz
agregasyon_mantigi = {
    'SK_ID_BUREAU (Kredi ID)': 'count', # Kişinin toplam kaç geçmiş kredisi var?
    'AMT_CREDIT_SUM (Toplam Kredi Limiti)': ['sum', 'mean', 'max'],
    'AMT_CREDIT_SUM_DEBT (Güncel Kalan Borç)': ['sum', 'mean'],
    'AMT_CREDIT_SUM_OVERDUE (Gecikmiş Tutar)': ['sum', 'max'],
    'DAYS_CREDIT (Kredinin Çekildiği Gün)': ['min', 'max', 'mean'],
    'CREDIT_ACTIVE (Kredi Durumu)_Active': 'sum',
    'CREDIT_ACTIVE (Kredi Durumu)_Closed': 'sum',
    'CREDIT_TYPE (Kredi Türü)_Consumer credit': 'sum',
    'CREDIT_TYPE (Kredi Türü)_Credit card': 'sum',
    'BB_MAX_OVERDUE_LEVEL': 'max',
    'BB_TOTAL_OVERDUE_SCORE': 'sum'
}

# 2. Müşteri ID'sine göre gruplayıp yukarıdaki mantığı uyguluyoruz.
# NOT: Hata aldığın yeri 'SK_ID_CURR' olarak düzelttik.
# Eğer hala hata verirse, buraya 'SK_ID_CURR (Ana Müşteri ID)' yazmayı deneyebilirsin.
bureau_tek_satir = bureau_merged.groupby('SK_ID_CURR').agg(agregasyon_mantigi)

# 3. Sütun isimlerini tek katmanlı hale getiriyoruz
yeni_sutun_isimleri = []
for col in bureau_tek_satir.columns.values:
    # İki katmanlı ismi birleştir (Örn: 'AMT_CREDIT_SUM' ve 'max' -> 'BUREAU_AMT_CREDIT_SUM_max')
    yeni_isim = 'BUREAU_' + col[0] + '_' + col[1]
    # İsimdeki parantez ve boşlukları temizleyelim ki model sorun yaşamasın
    yeni_isim = yeni_isim.replace(' (', '_').replace(')', '').replace(' ', '_')
    yeni_sutun_isimleri.append(yeni_isim)

bureau_tek_satir.columns = yeni_sutun_isimleri

# Müşteri ID'sini index'ten tekrar normal sütun haline getiriyoruz
bureau_tek_satir = bureau_tek_satir.reset_index()

print("İşlem tamam! Yeni boyut:", bureau_tek_satir.shape)
display(bureau_tek_satir.head())

bureau_tek_satir.head(10)

bureau_tek_satir.shape

# ==============================================================================
# BUREAU VERİSİNİ TEK SATIRA İNDİRGEME (AGGREGATION) MANTIĞI
# ------------------------------------------------------------------------------
# Amaç: Müşterinin (SK_ID_CURR) geçmişteki çoklu kredi kayıtlarını tek bir
# finansal profil (satır) haline getirmek. 34 kolondan, modelin kafasını
# karıştırmayacak en güçlü 18 kolonu (öz suyu) çıkarıyoruz.
#
# --- 1. KİMLİK (1 Kolon) ---
# SK_ID_CURR: Ana tablo ile birleştirmek için kullanacağımız müşteri numarası.
#
# --- 2. KREDİ SAYISI VE TÜRÜ (5 Kolon) ---
# BUREAU_SK_ID_BUREAU_count: Geçmişte çekilen toplam kredi sayısı.
# BUREAU_CREDIT_ACTIVE_Active_sum: Halen ödemesi devam eden aktif kredi sayısı.
# BUREAU_CREDIT_ACTIVE_Closed_sum: Başarıyla kapatılmış kredi sayısı.
# BUREAU_CREDIT_TYPE_Consumer_credit_sum: Toplam tüketici (ihtiyaç) kredisi sayısı.
# BUREAU_CREDIT_TYPE_Credit_card_sum: Toplam kredi kartı sayısı.
#
# --- 3. MİKTAR VE HACİM (5 Kolon) ---
# BUREAU_AMT_CREDIT_SUM_sum: Bugüne kadar alınan toplam kredi limiti.
# BUREAU_AMT_CREDIT_SUM_mean: Ortalama kredi çekme tutarı.
# BUREAU_AMT_CREDIT_SUM_max: Tek seferde çekilen en büyük kredi tutarı.
# BUREAU_AMT_CREDIT_SUM_DEBT_sum: Bankalara olan toplam güncel borç.
# BUREAU_AMT_CREDIT_SUM_DEBT_mean: Kredi başına düşen ortalama kalan borç.
#
# --- 4. GECİKME VE RİSK [EN KRİTİK BÖLÜM] (4 Kolon) ---
# BUREAU_AMT_CREDIT_SUM_OVERDUE_sum: Toplam gecikmiş (ödenmemiş) parasal tutar.
# BUREAU_AMT_CREDIT_SUM_OVERDUE_max: Tek seferde yapılan en büyük gecikme tutarı.
# BUREAU_BB_MAX_OVERDUE_LEVEL_max: (Balance'dan) Tarihindeki en kötü gecikme seviyesi.
# BUREAU_BB_TOTAL_OVERDUE_SCORE_sum: (Balance'dan) Ömür boyu yediği toplam gecikme skoru.
#
# --- 5. ZAMANLAMA (3 Kolon) ---
# BUREAU_DAYS_CREDIT_max: En son kredi çekilen tarih (Güncelliği gösterir).
# BUREAU_DAYS_CREDIT_min: İlk kredi çekilen tarih (Müşterilik kıdemi).
# BUREAU_DAYS_CREDIT_mean: Ortalama kredi çekme sıklığı.
#
# --- NEDEN 16 KOLONU SİLDİK? ---
# 1. Nadir görülen kredi türleri (Araba, Mortgage, Microloan vs.) ve durumları
#    (Bad debt, Sold) ezberi önlemek için silindi (Çoğu sıfırdı).
# 2. Çok fazla boşluk (NaN) içeren Planlanan/Fiili bitiş tarihleri silindi.
# 3. Kredi kartı limiti (%34'ü boştu) ve gereksiz vade uzatma sayıları atıldı.
# 4. Model için gürültü yaratacak tekrar eden gün/ay sayıları temizlendi.
# ==============================================================================
